### ISSUE TITLE
Frontinsampa 2016 - STAIRWAY TO HEAVEN

### ISSUE THREAD

**Issue by elvisdetona** [braziljs/weekly#105]
**[Frontinsampa 2016](http://www.frontinsampa.com.br)**

Do Inferno ao Paraíso. Quem já participou das quatro primeiras edições do Frontinsampa sabe que ano a ano o evento cresce, não é verdade? Para acompanhar essa evolução e receber palestrantes e participantes, a 5ª edição do evento será realizada em um novo endereço (Av. Bernardino de Campos, 79 - Próximo ao metrô Paraíso). Além da mudança de endereço, novos palestrantes também irão se apresentar no Frontinsampa 2016! O que não mudará no evento deste ano é o espírito do evento... Aprender, Compartilhar e se Divertir. 
Confirmados estāo #alganet #eduagni #mjcoffeeholick #talitapagani #almirfilho #reinaldoferraz e mais alguns... vem gente, inscreva-se e nāo fique de fora! 

*Eventos*

**Comment by elvisdetona** [comment]
Essa semana será agitada em Sāo Paulo... na Quinta-feira teremos MeetuCSS, na Sexta-feira o Code In The Dark, Sábado terá o Frontinsampa e Segunda e Terça, NodeConf 👍

**Comment by guilhermepontes** [comment]
#104?

**Comment by jaydson** [comment]
Valeu @elvisdetona ! Já coloquei na edição 104.
Obrigado por lembrar @guilhermepontes :)
