### ISSUE TITLE
Descrição do projeto no github

### ISSUE THREAD

**Issue by ftonato** [braziljs/weekly#157]
Como segue na imagem abaixo, há uma _url_ após a breve descrição do projeto, e essa _url_ já não existe mais (https://braziljs.org/#weekly).

![captura de tela 2017-05-30 as 15 16 44](https://cloud.githubusercontent.com/assets/5417662/26598303/4c0fcce0-454b-11e7-8f77-1a17339c39b3.png)

**Comment by jaydson** [comment]
Done.
