### ISSUE TITLE
Sessão de Jobs

### ISSUE THREAD

**Issue by thulioph** [braziljs/weekly#185]
Eu não sei se é válido, ou se já foi pensado algo nesse tipo.. Mas o que vocês acham de adicionar uma sessão **jobs** para weekly? 

Podia rolar uma curadoria das vagas do [Frontendbr](https://github.com/frontendbr/vagas/issues)  e juntar as forças para além de compartilhar conteúdo, compartilhar possíveis jobs. 

Já tinha visto essa proposta em outras weeklys, e queria saber a opinião de vocês. Eai?

cc: @jaydson @LFeh

**Comment by LFeh** [comment]
Opa, já temos uma integração com o Twitter que funciona muito bem. 

Seria bem legal uma no Weekly da BrazilJS, aparecem vagas super relevantes nesse repositório :)

**Comment by renanbastos93** [comment]
Opa, acho bem interessante essa ideia, de poder compartilhar JOBs com a galera, pois certeza que muitos que acompanham a Weekly, também está a procura de um emprego ou freela.

**Comment by ruanmer** [comment]
Mas como definir quais vagas apareceriam na weekly ou não? Talvez seja melhor só um link com destaque pro github do frontendbr.

**Comment by thulioph** [comment]
Eu acredito que tentar nivelar é o ideal. Vagas de junior, pleno, senior, remoto, etc.. Um pouco do que rolou na semana relacionada a weekly.

**Comment by thulioph** [comment]
Como referência, eu conheço a [Frontend Focus](https://frontendfoc.us/issues/319) e a [Javascript Weekly](http://javascriptweekly.com/issues/363) que possuem uma sessão **jobs**.

**Comment by mikejavier** [comment]
Na mesma pegada do Frontend Focus, o [VuejsFeed](https://vuejsfeed.com/) tb rola a seção jobs na weekly. Seria interessante a brasiljs ter.
