### ISSUE TITLE
Sessão separada da Weekly no site

### ISSUE THREAD

**Issue by chrisgfortes** [braziljs/weekly#200]
**Criação de uma categoria no site para a BrazilJS Weekly**
Eai pessoal, acompanho vocês na weekly toda a semana, e as vezes acabamos não assistindo todos os videos no momento que é lançado, para ter uma fácil localização, vocês poderiam criar uma sessão separada no site e manter atualizado com todas as Weeklys.

Valeu!
_Site_

**Comment by felipenmoura** [comment]
Legal @chrisgfortes boa ideia.
Temos feito isso com uma playlist no nosso canal no youtube:
https://www.youtube.com/watch?v=Bq0oD8r7aas&list=PLg2lQYZDBwOQDXKxy9yeqXG5njHbSHFFD
Mas realmente, ter isso no site seria legal.
Nós meio que temos uma categoria no site (que poderia ser um pouco mais organizada, na verdade):
https://braziljs.org/?s=weekly

Acho que uma sessão só pra isso faz sentido, ou quem sabe, uma forma de embedar a playlist do youtube, mesmo.
