### ISSUE TITLE
React 16.3 Adeus Redux ?

### ISSUE THREAD

**Issue by devalexandre** [braziljs/weekly#204]
**[React 16.3 sem Redux](http://www.indev.net.br/post/react-163-sem-redux)**

Com a declaração do criador do redux, sobre descontinuar o projeto e a implementação na api context do React 16.3, os desenvolvedores, terão  uma alternativa mais simples, para manipulação do state sem precisar usar libs de terceiros.

*Categoria*
Artigos, News

**Comment by oieduardorabelo** [comment]
olá @devalexandre 👋,

para contribuir com a weekly, a issue da newsletter é nessa url abaixo:

https://github.com/braziljs/weekly/issues/203

bastar adicionar um novo comentário no mesmo formato que você criou aqui,

essa issue está no lugar errado, você pode fecha-lá 🤗
