### ISSUE TITLE
Criar uma alternativa para assinar a Weekly

### ISSUE THREAD

**Issue by felquis** [braziljs/weekly#24]
Atualmente a única forma de aderir a Weekly é quando esta vendo uma Weekly no browser, e no topo fica um input para entrar com o e-mail, minha sugestão que que [nesta página](http://braziljs.org/services/add2weekly/) exista este input para que não assinantes possam aderir a weekly ou algo similar.

**Comment by keppelen** [comment]
Ainda tem algo para issue @felquis ?
