### ISSUE TITLE
Componentização no front end - conceito

### ISSUE THREAD

**Issue by Demysdcl** [braziljs/weekly#248]
Componentização no front end - conceito

Explicando o conceito de componentização fazendo uma comparação com um carro.

[Componentização no front end](https://inside.contabilizei.com.br/componentiza%C3%A7%C3%A3o-no-front-end-3fc889a363df)

Front end

**Comment by filipedeschamps** [comment]
@Demysdcl você deve postar o conteúdo nessa issue -> https://github.com/braziljs/weekly/issues/247
