### ISSUE TITLE
Para iniciar em Data Science

### ISSUE THREAD

**Issue by leticiadasilva** [braziljs/weekly#276]
**[Para iniciar em Data Science](https://colaboradados.github.io/blogposts/para-iniciar-em-data-science.html)**

Manual para começar em Ciência de Dados, repleto de dicas de materiais gratuitos. Foi produzido por Letícia Silva especialmente para o [Colaboradados](https://colaboradados.github.io/), o veículo colaborativo sobre Transparência e Open Data no Brasil.

*Artigo
![photo_2019-07-08_21-33-24](https://user-images.githubusercontent.com/28828381/60851047-2ce13a80-a1c8-11e9-9764-1714ac0b4046.jpg)
*

**Comment by oieduardorabelo** [comment]
oi @leticiadasilva você acabou criando uma nova issue, onde eu acredito que seria um comentário na weekly aberta em https://github.com/braziljs/weekly/issues/275 😄, comenta lá para compartilhar seu link dia 11/07!

**Comment by leticiadasilva** [comment]
Oi Eduardo, perdão! Tô tão cansada que nem percebi :/

Vou lá arrumar, muito obrigada!

Atenciosamente,
Letícia Silva.

Laboratório Associado de Computação e Matemática Aplicada - LAC
Instituto Nacional de Pesquisas Espaciais - INPE

contato_leticiasilva@hotmail.com
leticiadasilva.contato@gmail.com


Em ter, 9 de jul de 2019 às 00:59, Eduardo Rabelo <notifications@github.com>
escreveu:

**Comment by leticiadasilva** [comment]
Obs: Fui apagar aqui, porém não tenho permissão. Se puder fazer isso, agradeço. Já comentei na issue aberta.
