### ISSUE TITLE
Evento: Como Testar Seu Sofware - Workshop de Testes Automatizados

### ISSUE THREAD

**Issue by paulodiovani** [braziljs/weekly#313]
# **[Como Testar Seu Sofware - Workshop de Testes Automatizados](https://www.meetup.com/valetechtalks/events/268854460/)**

O Workshop de Testes Automatizados foi planejado para profissionais e estudantes de computação em geral.

Iremos abordar diferentes linguagens, incluindo como criar um ambiente de testes, quais são as boas práticas e quais as principais partes do software que devem ser testadas.

O workshop é gratuíto e aberto a todas as pessoas. Confiram nosso código de conduta em https://valetechtalks.github.io/codeofconduct.html.

## Categoria

- Eventos

## Local e Data

**Universidade Feevale - Câmpus II**
_RS-239 · Novo Hamburgo_
Salão de Exposições do Prédio Arenito

Dia *21 de Março de 2020** a partir das **13:00** horas

## Links

- Evento no Meetup.com https://www.meetup.com/valetechtalks/events/268854460/
- Página do grupo https://valetechtalks.github.io/
- Código de Conduta https://valetechtalks.github.io/codeofconduct.html

## Folder para Divulgação

https://drive.google.com/open?id=1WFIgqMGnv-G1NvX8MKAcbhC2sJGMDxBB

![Folder](https://user-images.githubusercontent.com/1295197/75998668-ef13ed80-5edf-11ea-98b5-b93b6f3ec4b2.png)

**Comment by jaydson** [comment]
@paulodiovani fechando essa issue aqui pois temos um sistema automático de leitura das issues.
Esse sistema precisa que a issue atual da Weekly siga o formato que está na descrição.
De qualquer forma, vou incluir na seção de eventos dessa edição.
Valeu!
