### ISSUE TITLE
Weekly + colaborativa

### ISSUE THREAD

**Issue by jaydson** [braziljs/weekly#38]
"Cuidei" da Weekly por quase um ano (eu acho), fazendo a coleta, edição, revisão, etc.
É um trabalho legal, consome algumas horas, mas no final é prazeroso.
Com o tempo, o prazer vai embora, e precisamos de uma injeção de ânimo.

Minha ideia aqui é tornar a Weekly ainda mais colaborativa via Github e não mais somente pelo envio de sugestões via ad2weekly.
O que acham?

Eu me responsabilizo por gerenciar isso no começo.
Crio uma issue por semana (Ex: "BrazilJS Weekly #98"), e coletamos comentários e sugestões nesta issue.
Acho que isso pode nos dar agilidade, auto-curadoria, auto-revisão e outros benefícios que não sou capaz de prever agora.
Outra coisa legal é que teremos um histórico da criação das Weeklys, o que pode ser interessante.
Além disso, podemos revezar o gerenciamento disso, fazendo com que o peso não fique só com uma pessoa.

Outro ponto positivo é a transparência, fica tudo visível para todos.

//cc @felipenmoura @zenorocha @felquis @jugoncalves @keppelen

**Comment by jugoncalves** [comment]
Acho uma ótima ideia. :+1: Inclusive, me predisponho a "cuidar" da Weekly 1x por mês ou quando precisarem (todos temos essas semanas que magicamente viram um inferno.)

**Comment by keppelen** [comment]
Eu gosto e fiquei pensando em uma coisa.

Podemos criar algo como os posts do blog, assim cada Weekly teria um post .md, o DocPad geraria esse html, e via API do Mailchimp disparamos a weekly.

Outra opção e tentar uma pareceria com SendGrid, e usar a API deles, que seria melhor é mais fácil  de desenvolver.

Assim toda a Weekly ficaria por aqui, e claro, teríamos um "editor" que iria aprovar os posts e aceitar os 
Pull Request.

**Comment by luiztiago** [comment]
Acho que mais simples e bem colaborativo, seria criar arquivos .md para cada semana da weekly, e as sugestões seriam feitas via Pull Request. A coisa mais comum que todo mundo tá acostumado, e ficaria o registro das weeklys no próprio repositório.

**Comment by jugoncalves** [comment]
concordo com o @luiztiago.

**Comment by luiztiago** [comment]
Ou cria um arquivo para cada semana, ou deixa o README.me com o conteúdo e gera tags para cada semana quando tiver concluída.

Independente da forma, os Pull requests seriam revisados e mergeados (ou fechados).

**Comment by felquis** [comment]
Criar várias issues "Weekly X", "Weekly Y", os comentários são links para
serem adicionados na Weekly.

Se for pra mandar um pull request pra colaborar na weekly, meu deus, muito
trabalhoso.

Em 4 de fevereiro de 2015 12:23, Luiz Tiago Oliveira <
notifications@github.com> escreveu:

> Ou cria um arquivo para cada semana, ou deixa o README.me com o conteúdo e
> gera tags para cada semana quando tiver concluída.
>
> Independente da forma, os Pull requests seriam revisados e mergeados (ou
> fechados).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braziljs/weekly/issues/38#issuecomment-72861677>.
>



-- 
Felquis Gimenes - Front-end
felquis.com +55 011 95980 2233

**Comment by luiztiago** [comment]
Acho que também funciona. O ruim das issues, é que tem praticamente o mesmo trabalho de hoje.

A ideia dos pull requests seria tirar a responsabilidade de uma única pessoa para organizar a weekly. Dividir o trabalho para todo mundo?

**Comment by jugoncalves** [comment]
Acho que deve abrir uma `Weekly#xxx.md` por semana e dai as pessoas podem ir mandando PR durante os dias. No dia de publicar, alguém resolve as sugestões, publica, fecha essa e abre a próxima. E assim vai.

**Comment by jaydson** [comment]
Abri PR pra enviar uma dica eu acho inviável.
Pra abir um PR, é preciso forkar o projeto, fazer alteração, fazer push pro fork e só depois enviar a dica.
A minha ideia da issue é tentar fazer com que seja fácil gerar um discussão e dar uma dica, e issues do Github facilitam isso.

> O ruim das issues, é que tem praticamente o mesmo trabalho de hoje.

Não concordo @luiztiago , hoje não sabemos quem mandou o link, e não podemos gerar um discussão e revisão em cima disso, entende?

@keppelen gostei da ideia! Pode funcionar legal isso.
Só acho que temos elaborar bem isso.

**Comment by luiztiago** [comment]
@jaydson O github atualmente deixa você abrir um PR editando o arquivo direto no repositório, pelo próprio site do github. No final das contas, ele mesmo faz o fork, altera, e abre o PR.

**Comment by jaydson** [comment]
Mas mesmo assim. Eu nem sabia que existia isso.
Qual a vantagem disso eu relação as issues?

Notem que a ideia é ter apenas uma issue por Weekly, a as dicas são comentárlos.
Acho isso muita mais fácil de lidar.
Estou tentando trazer o que já temos em software para criar a Weekly.
Debates, sugestões, revisão, etc.

Um PR estaria de acordo se cada pessoa fosse fazer uma Weekly inteira, o que não é o que queremos. 
Queremos ter auto-curadoria, transparência na escolha dos links e discussões relevantes, IMHO.

**Comment by jugoncalves** [comment]
A vantagem é vc não precisa clonar repositório, pode editar na interface mesmo.

**Comment by luiztiago** [comment]
Então, tá lindo! :)

A ideia é facilitar e ajudar. Você tem muito mais experiência com as weeklys do que eu.  Se assim já vai ajudar o processo, :+1:.

**Comment by luiztiago** [comment]
Isso, @jugoncalves

**Comment by thiagopnts** [comment]
Outra vantagem de usar PRs é que daria pra ter alguma discussão sobre o link dentro do PR, mas não sei se esse é o objetivo do negócio.

**Comment by jaydson** [comment]
Acho que com PR's não fica bom mesmo.
E se tivermos 30 dicas? Seriam 30 PR's.
Fica meio sem sentido. Além de que os PR's teriam q ser aprovados ou não, um a um.
Com a issue acho que fica mais centralizado e fácil de manter.

**Comment by jugoncalves** [comment]
Que tal tentar uma vez com issues pra gente vê o que dá? :)

**Comment by jaydson** [comment]
Boa @jugoncalves :)
Vamos evoluindo conforme for.

**Comment by keppelen** [comment]
Mas pelo que entendi bem, essa ideia da issues, todos assinantes teriam que vir no github olhar a weekly, ai eu já não acho certo, estamos falando para pessoas como a gente que cosutma olhar o github todo dia.

Mas tem muitas pessoas na weekly que so ve o email. Acho que ter o github com MD para weekly e um processo jutando tudo isso e mandando o email, seria o melhor caso. E ainda continuaria tendo as issues aqui para discutir links, transparencia, etc.

@jaydson podemos tentar fazer um mock. Vou falar com @heitortsergent para uma possível parceria com nossa conta.

**Comment by jaydson** [comment]
@keppelen a ideia aqui é melhorar o processo de produção da Weekly.
Interessados em ajudar podem vir aqui e contribuir.
Quem quiser continuar mandando link pelo bookmarklet ou addon, vai poder.
Aqui no Github é o processo de curadoria dos links.
Quem apenas recebe no email, continurá normalmente recebendo.

**Comment by keppelen** [comment]
Agora sim entendi. E porque a ideia que tinha dado, a montagem ficava meio que automatizado. Mas agora entendi as 2 coisas. Da para unir.

**Comment by jugoncalves** [comment]
:+1:

**Comment by zenorocha** [comment]
Dado que a ideia foi aceita pela comunidade e tem dado certo, acho que podemos fechar essa issue :)

**Comment by felquis** [comment]
Só gostaria de dar meu feedback sobre o que está rolando na issue #39, 

Estou amando profundamente isso, sem contar que fico constantemente recebendo os emails das outras sugestões, acaba que eu fico todos os dias ou sendo lembrado que ainda da pra mandar links ou já vendo algumas novidades por ai.

Achei sensacional o trabalho na issue porque engaja muito mais todo mundo que participa ou pretende participar, enviar sugestões de links add2weekly é bem monótono comparada a issue e acaba que uns 20 mais ou menos profissionais que se envolvem na issue, gerará um ótimo conteúdo para as outras centenas de profissionais que recebem a Weekly por email.

Enfim, parabéns, acho que dará muito certo usar as issues :D

**Comment by jaydson** [comment]
Valeu pelo feedback @felquis , a ideia realmente superou minhas expectativas :)
