### ISSUE TITLE
Weekly extraordinária

### ISSUE THREAD

**Issue by jaydson** [braziljs/weekly#42]
Pessoal, todos devem ter visto a campanha para ajudar o Leonardo Konarzewski hoje, quem não viu, veja: http://leokz.com/campanha/
Pensei em fazer uma Weekly extraordinária para tentar ajudar, que acham?

**Comment by fdaciuk** [comment]
Super válido @jaydson :+1:

**Comment by jaydson** [comment]
Já falei com o Leonardo e ele achou uma boa.

**Comment by fdaciuk** [comment]
Vai ser uma weekly só com o vídeo dele e os links para doação?

**Comment by jaydson** [comment]
Não sei ainda, aceito sugestões.

**Comment by fdaciuk** [comment]
Acho que seria legal montar algo nesse estilo:
* Um texto curto, de introdução; 
* o vídeo em destaque, ocupando toda a largura;
* abaixo do vídeo as informações de como doar, com os dados bancários, link para o PagSeguro dele e para o site dele, na página da campanha :)

**Comment by jaydson** [comment]
Agendei para ser disparada amanhã as 10h.
http://us5.campaign-archive1.com/?u=77b6594f10bba05dcc722c80e&id=e1d599498b

Podem conferir se está ok?

**Comment by fdaciuk** [comment]
Top! Bem simples e com foco no que precisa :clap: :clap: :+1: 

Ótima iniciativa cara :D
:dancer: :dancer:

**Comment by letanure** [comment]
:+1:  muito bom

**Comment by felquis** [comment]
:clap:
