### ISSUE TITLE
Alteração texto - evento Conferência CSS Brasil

### ISSUE THREAD

**Issue by raphaelfabeni** [braziljs/weekly#46]
Fala pessoal, tudo bem?
Abri essa issue em relação ao call for papers da Conferência CSS Brasil. 
O texto aponta um link para o call, mas [ele já foi encerrado](https://docs.google.com/forms/d/18BK5tG_9uxe16fVK8NhNgjbs9PhdAeb9rv-hqaiBoPY/closedform).
Valeu gente!

**Comment by jaydson** [comment]
Valeu cara! Na próxima eu arrumo
