### ISSUE TITLE
Artigo sobre módulos em JS

### ISSUE THREAD

**Issue by tiagorg** [braziljs/weekly#48]
Pessoal, acabei de publicar este artigo sobre modules em JavaScript! Talvez interesse para a Weekly:  https://www.airpair.com/javascript/posts/the-mind-boggling-universe-of-javascript-modules

**Comment by jugoncalves** [comment]
@tiagorg sugira seu artigo [nessa thread](https://github.com/braziljs/weekly/issues/47).

**Comment by tiagorg** [comment]
pronto @jugoncalves, obrigado!

**Comment by jugoncalves** [comment]
:smile:
