### ISSUE TITLE
BrazilJS Weekly & www.braziljs.org

### ISSUE THREAD

**Issue by learningjs** [braziljs/weekly#55]
1 Confirmar assinatura (mail)
2 clicar em "continuar para o nosso site" (na pagina de confirma)
3 vai para [www.braziljs.org](http://www.braziljs.org/)
4 "This webpage is not available"
5 fix: [braziljs.org/](http://braziljs.org/)

**Comment by raphaelpor** [comment]
Acredito que já podemos fechar essa issue. :wink:

**Comment by felipenmoura** [comment]
yep ;)
