### ISSUE TITLE
O Java Script que você deveria conhecer - POST

### ISSUE THREAD

**Issue by pedropolisenso** [braziljs/weekly#68]
E ai pessoal, tudo certo? no dia 01/09 eu e alguns amigos conversávamos sobre como é importante saber alguns conceitos de programação e conceitos de engenharai de software. Então tive a ideia de criar um post relatando o que havia aprendido de teorias/cocneitos em cursos que ja havia feito, em experiências aplicadas no trabalho e compartilhar isso com a galera. Criei um post simples no Medium que relata conceitos e funções simples e básicas, mas que é muito importante saber.

PS: Feedbacks são bem vindos!

https://medium.com/@pedropolisenso/o-javasscript-que-voc%C3%AA-deveria-conhecer-b70e94d1d706

**Comment by jaydson** [comment]
Coloca na issue aberta da Weekly pra sair na próxima @pedropolisenso.
#67

**Comment by pedropolisenso** [comment]
Beleza @jaydson já foi!
