### ISSUE TITLE
Lista de podcasts

### ISSUE THREAD

**Issue by ogilvieira** [braziljs/weekly#71]
Com a ajuda de uma galera, criamos uma lista de podcasts focados em programação, ciências da computação, web em geral... quem sabe podem incluir na próxima weekly:

https://github.com/ogilvieira/dev-podcast-list-brazil

Valeu!

**Comment by ogilvieira** [comment]
sugestão movida para a issue da próxima campanha #70

**Comment by jaydson** [comment]
:+1:

**Comment by jugoncalves** [comment]
Seria legal ter um arquivo de contribuiting pra ajudar o pessoal a não abrir essas issues sem querer.

**Comment by jaydson** [comment]
Boa @jugoncalves !
Vou fazer.
