### ISSUE TITLE
Categorias disponíveis

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/weekly#75]
Quais são todas as categorias de links?

Ex: `Artigos`, `Tools, demos e outros`...

Seria legal listar no README e no comment inicial isso :smile:

**Comment by jaydson** [comment]
Boa dica @ericdouglas, obrigado :)
Vou colocar no README isso.

**Comment by jaydson** [comment]
Veja como ficou @ericdouglas 
https://github.com/braziljs/weekly/issues/74

Que acha?

**Comment by ericdouglas** [comment]
@jaydson excelente! Era isso mesmo :wink:
