### ISSUE TITLE
Novo design para a newsletter

### ISSUE THREAD

**Issue by jaydson** [braziljs/weekly#86]
Atualamente, o design do email da Weekly é bem simples.
![screenshot from 2015-12-01 23 58 26](https://cloud.githubusercontent.com/assets/72206/11520126/75cf39a2-9887-11e5-9d1b-7d563529626e.png)

Precisamos criar um novo design, mais bonito, moderno e responsivo.

//cc @italowaxman
//cc Outros designers que queiram contribuir

**Comment by djalmaaraujo** [comment]
Fica como o dica o design da CSS weekly.
Mas no geral eu acho bem legal o atual é clean.
Seria IDEAL a weekly e os videos seguirem o mesmo padrão visual, ter uma identidade. Sei que isso é algo mais complexo pro momento, mas seria um "IDEAL".

Abs

![screenshot 2015-12-16 11 07 57](https://cloud.githubusercontent.com/assets/3402/11842893/502199f2-a3e5-11e5-954d-fbeffde7ed33.png)
![screenshot 2015-12-16 11 08 04](https://cloud.githubusercontent.com/assets/3402/11842894/5024d036-a3e5-11e5-8f70-6eaa24e88a5b.png)

**Comment by thulioph** [comment]
Eu gosto da disposição dos elementos e harmonia do **CSS Weekly**, se pudesse criar essa identidade eu acho válido também :)

**Comment by jaydson** [comment]
Boa @djalmaaraujo ! Valeu!
Vamos ver se rola fazer algo nesse sentido @thulioph .

**Comment by thulioph** [comment]
O **Javascript weekly** possui uma sessão que eu acho bem interessante, `jobs`. 
O que acham de adicionar esse espaço?

o/

<img width="717" alt="screen shot 2015-12-18 at 2 33 34 pm" src="https://cloud.githubusercontent.com/assets/2343288/11902970/5eb325a2-a594-11e5-8cf8-821a49106b67.png">

**Comment by vitortalaia** [comment]
Acho bacana também o formato do [Front-end Dev Weekly](https://frontenddevweekly.curated.co/issues).

![screenshot from 2015-12-18 17 40 59](https://cloud.githubusercontent.com/assets/5838414/11905618/a219591e-a5ae-11e5-91ef-7d6be2ceb6fa.png)

**Comment by gutierri** [comment]
Fazer algo parecido com o Front-end Dev Weekly, que o @vitortalaia parece bom também. O layout é limpo e isso é bom ;)

**Comment by jaydson** [comment]
Fechando essa issue pois criei um novo template baseado em um do próprio Mailchimp.
Obrigao pelas dicas pessoal :)

![screenshot from 2016-03-10 03 19 17](https://cloud.githubusercontent.com/assets/72206/13661165/ea03cb0a-e66e-11e5-8a00-24ded750f262.png)
