### ISSUE TITLE
Campaign 142 - 07/04/2016

### ISSUE THREAD

**Issue by felipenmoura** [braziljs/weekly#94]
Weekly a ser disparada no dia 07/04/2016

Ajude a BrazilJS Weekly postando sua dica, link ou sugestão aqui nos comentários desta issue.
Ao longo da semana vamos debatendo e juntando os melhores links que serão inseridos na próxima Weekly.

### Template para uma boa dica (Não é obrigatório, faça como quiser):
```
**[Título](URL)**
Rápida descrição
*Categoria*
```

### Exemplo de dica:
__[lodash-decorators](https://github.com/steelsojka/lodash-decorators)__
Uma coleção de decorators usando o lodash.
_Tools_

### Categoria:
Para a categoria, escolha em qual contexto o link melhor se encaixa.
Alguns dos exemplos de categorias mais utillizadas: `Artigos`, `News`, `Videos`, `Eventos`, `Tools`, `Demos e outros`

PS: Thumbs up para quem seguir os exemplos, pois facilita MUITO a vida de quem edita a news no Mailchimp (posso só copiar e colar lá).

**Comment by CezarLuiz0** [comment]
**[Ginder - Redux, ES6, VueJS e CSS4](http://cezarluiz0.github.io/Ginder/)**
Ginder é um experimento feito com Redux, ES6 nativo, VueJS e variáveis nativas do CSS. Para ver o experimento, use o Chrome 49+ ou Firefox 44+.
*Demos*

**Comment by FagnerMartinsBrack** [comment]
**[Roubo dos pacotes do NPM na perspectiva dos ladrões](https://medium.freecodecamp.com/npm-package-hijacking-from-the-hijackers-perspective-af0c48ab9922)**
Um texto que conta como o usuário @nj48 conseguiu obter em poucos minutos todos os módulos do npm que foram liberados por Azer e entregá-los com segurança antes que um dano maior fosse causado.
*News*

**Comment by luizcaciatori** [comment]
**[Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)**
Repositório com o Style Guide de JavaScript usado pelos desenvolvedores na Airbnb.
*outros*

**Comment by glaucocustodio** [comment]
**[RuPy Campinas 2016 - Inscrições Abertas](http://campinas.rupy.com.br/)**
O evento para apaixonados por desenvolvimento chega à sua segunda edição. Ruby, Python, JavaScript e o que há de mais incrível..
*Eventos*

**Comment by FagnerMartinsBrack** [comment]
**[Promises + Sync Code = Disaster](https://medium.com/@fagnerbrack/promises-sync-code-disaster-e9d41a3c7279)**
A melhor forma de tornar o seu código difícil de manter é rodar operações síncronas disfarçadas de operações assíncronas.
*Artigos*

**Comment by willianjusten** [comment]
**[Best Web Developer Podcasts for 2016](http://thenewcode.com/997/Best-Web-Developer-Podcasts-For-2016)**
Um conjunto de podcasts feitos por desenvolvedores.
*Artigos*
