### ISSUE TITLE
(CLOSE) ECMAScript 2015 (ES6) Tutorial with Babel 6 and Webpack

### ISSUE THREAD

**Issue by geisonsn** [braziljs/weekly#99]
*[ECMAScript 2015 (ES6) Tutorial with Babel 6 and Webpack](http://ccoenraets.github.io/es6-tutorial/index.html)**

Tutorial simples e prático que ensina a como configurar o Babel e explica alguns recursos básicos do ES6

*Artigos*

**Comment by FagnerMartinsBrack** [comment]
Shouldn't this be created in the [weekly issue](https://github.com/braziljs/weekly/issues/98)?

**Comment by geisonsn** [comment]
Yes. And I was not able to remove, so I added the 'close' prefix to the title. I've added in the weekly issue.

**Comment by FagnerMartinsBrack** [comment]
@geisonsn That's weird, can't you close using the button in the side of "comment"?

**Comment by geisonsn** [comment]
@FagnerMartinsBrack No. The close button is not show for the issue.

**Comment by FagnerMartinsBrack** [comment]
That's weird, @jaydson?
